INSERT INTO GENRE(ID, NAME)
VALUES (1, 'fantasy');
INSERT INTO GENRE(ID, NAME)
VALUES (2, 'fantastic');

INSERT INTO FILMS(ID, TITLE, GENRE_ID)
VALUES (1, 'HURRY POTTER', 1);
INSERT INTO FILMS(ID, TITLE, GENRE_ID)
VALUES (2, 'BACK TO THE FUTURE', 2);

INSERT INTO PLACE(ID, NAME, FILM_ID)
VALUES (1, 'LONDON SQUARE', 1);
INSERT INTO PLACE(ID, NAME, FILM_ID)
VALUES (2, 'TRAIN', 1);
INSERT INTO PLACE(ID, NAME, FILM_ID)
VALUES (3, 'USA', 1);
